[package]
name = "invoice-rs"
version = "0.1.0"
edition = "2021"
authors = ["sandmannmax <mail@mxsandmann.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
